# Database
spring.application.name=maronnodes
spring.datasource.url=jdbc:postgresql://demone.edia.cloud:5459/maronnodes
spring.datasource.username=carl
spring.datasource.password=pondsama
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq.edia.cloud
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=adminpassword
spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=5

spring.docker.compose.enabled=false

# Spring Security
spring.security.enabled=false