name: Ansible Polygon

on:
  workflow_dispatch:
    inputs:
      server_ip:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      blockchain:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Parse inputs
        run: |
          echo "SERVER_IP=${{ github.event.inputs.server_ip }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ github.event.inputs.ssh_user }}" >> $GITHUB_ENV
          echo "BLOCKCHAIN=${{ github.event.inputs.blockchain }}" >> $GITHUB_ENV

      - name: Write SSH key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_PRIV }}" > ansible/ssh_key
          chmod 600 ansible/ssh_key

      - name: Install Ansible
        uses: alex-oleshkevich/setup-ansible@v1
        with:
          version: "9.3.0"

      - name: Print Ansible version
        run: ansible-playbook --version

      - name: Run Ansible playbook
        run: |
          ANSIBLE_SSH_ARGS='-o StrictHostKeyChecking=no' \
          ansible-playbook \
            -i "$SERVER_IP," \
            -u "$SSH_USER" \
            --private-key ansible/ssh_key \
            -e "@ansible/common_vars/all.yaml" \
            -e "blockchain_type=$BLOCKCHAIN" \
            infra/ansible/site.yml
