name: Ansible Polygon

on:
  workflow_dispatch:
    inputs:
      server_ip:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      blockchain:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Parse inputs
        run: |
          echo "SERVER_IP=${{ github.event.inputs.server_ip }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ github.event.inputs.ssh_user }}" >> $GITHUB_ENV
          echo "BLOCKCHAIN=${{ github.event.inputs.blockchain }}" >> $GITHUB_ENV

      - name: Install Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: "2.15.13"

      - name: Check Ansible version
        run: ansible-playbook --version

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: infra/ansible/site.yml
          directory: ./
          key: ${{ secrets.ANSIBLE_SSH_PRIV }}
          inventory: |
            [all]
            ${{ env.SERVER_IP }} ansible_user=${{ env.SSH_USER }}
          options: |
            --extra-vars "blockchain_type=${{ env.BLOCKCHAIN }}"
            --extra-vars "@ansible/common_vars/all.yaml"
            --verbose