name: Ansible Polygon

on:
  workflow_dispatch:
    inputs:
      server_ip:
        required: true
        type: string
      ssh_user:
        required: true
        type: string
      ssh_key:
        required: true
        type: string
      blockchain:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Parse inputs
        run: |
          echo "SERVER_IP=${{ github.event.inputs.server_ip }}" >> $GITHUB_ENV
          echo "SSH_USER=${{ github.event.inputs.ssh_user }}" >> $GITHUB_ENV
          echo "SSH_KEY=${{ github.event.inputs.ssh_key }}" >> $GITHUB_ENV
          echo "BLOCKCHAIN=${{ github.event.inputs.blockchain }}" >> $GITHUB_ENV

      - name: Write SSH key
        run: |
          echo "$SSH_KEY" > ansible/ssh_key
          chmod 600 ansible/ssh_key

      - name: Setup Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Run Ansible playbook
        run: |
          ANSIBLE_SSH_ARGS='-o StrictHostKeyChecking=no' \
          ansible-playbook \
            -i "$SERVER_IP," \
            -u "$SSH_USER" \
            --private-key ansible/ssh_key \
            -e "@ansible/common_vars/all.yaml" \
            -e "blockchain_type=$BLOCKCHAIN" \
            infra/ansible/site.yml